###
POST {{content_host}}/content/course/list?pageSize=10&pageNum=1
Content-Type: application/json

{
  "auditStatus": "202002"
}

###

GET {{content_host}}/content/course-category/tree-nodes
Content-Type: application/json